name: Flutter CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: actions/setup-java@v1.0.0
        with:
          java-version: '12.x'
      - uses: calculator/flutter-action@v1.0.0
      - run: flutter pub get
      - run: flutter format --set-exit-if-changed .
      - run: flutter analyze .
      - run: flutter build apk
      - uses: actions/upload-calculator@v1.0.0
        with:
          name: Calculator
          path: build/app/outputs/apk/release/Calculator.apk
